--- MAGNITUDE ANALYSIS ---

-- Find total customers by countries

select * from gold.dim_customers
select 
country,count(customer_key) total_customers
from gold.dim_customers
group by country
order by total_customers desc

-- Find total customers by gender

select
gender,count(customer_key) total_customers
from gold.dim_customers
group by gender
order by total_customers desc

-- Find total products by category

select
category,count(product_key) total_products
from gold.dim_products
group by category
order by total_products desc

-- What is the average costs in each category?

select
category,avg(product_key) avg_cost
from gold.dim_products
group by category
order by avg_cost desc

-- What is the total revenue generated for each category?

select
p.category,
sum(s.sales_amount) total_revenue
from gold.dim_products p
left join gold.fact_sales s
on  p.product_key = s.product_key
group by p.category
order by total_revenue desc


select
category,sum(sales_amount) from (
select
p.category,
s.sales_amount
from gold.dim_products p
left join gold.fact_sales s
on p.product_key = s.product_key
)t
group by category

-- What is the total revenue generated by each customer?

select 
c.customer_id,
c.first_name,
c.last_name,
sum(s.sales_amount) total_revenue
from gold.fact_sales s
left join gold.dim_customers c
on s.customer_key = c.customer_key
group by c.customer_id,
		 c.first_name,
		 c.last_name
order by total_revenue desc

-- What is the distribution of sold items across countries?

select
c.country,
sum(s.quantity) as total_items
from gold.fact_sales s
left join gold.dim_customers c
on c.customer_key=s.customer_key
group by c.country
order by total_items desc
